// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AddRoot(arg1:string,arg2:string):Promise<any>;

export function ChooseRoot():Promise<any>;

export function CopyText(arg1:string):Promise<void>;

export function Explain(arg1:string,arg2:string):Promise<app.ExplainView>;

export function Invalidate(arg1:string,arg2:string):Promise<app.ScriptView>;

export function OpenRoot(arg1:string):Promise<app.RootView>;

export function RefreshGit(arg1:string):Promise<app.GitRefresh>;

export function RemoveRoot(arg1:string):Promise<any>;

export function RenderDocument(arg1:string,arg2:string,arg3:string):Promise<app.DocumentView>;

export function RevealFile(arg1:string):Promise<void>;

export function RunScript(arg1:string,arg2:string,arg3:Array<string>,arg4:boolean):Promise<app.RunView>;

export function SendInput(arg1:string,arg2:string):Promise<void>;

export function Status():Promise<app.Status>;

export function StopScript(arg1:string):Promise<void>;

export function ToggleFavorite(arg1:string,arg2:string):Promise<any>;

export function Toolchains():Promise<Array<app.Toolchain>>;

export function Workspace():Promise<any>;
