// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRoot(arg1, arg2) {
  return window['go']['main']['App']['AddRoot'](arg1, arg2);
}

export function ChooseRoot() {
  return window['go']['main']['App']['ChooseRoot']();
}

export function Explain(arg1, arg2) {
  return window['go']['main']['App']['Explain'](arg1, arg2);
}

export function Invalidate(arg1, arg2) {
  return window['go']['main']['App']['Invalidate'](arg1, arg2);
}

export function OpenRoot(arg1) {
  return window['go']['main']['App']['OpenRoot'](arg1);
}

export function RemoveRoot(arg1) {
  return window['go']['main']['App']['RemoveRoot'](arg1);
}

export function RenderDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenderDocument'](arg1, arg2, arg3);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function ToggleFavorite(arg1, arg2) {
  return window['go']['main']['App']['ToggleFavorite'](arg1, arg2);
}

export function Toolchains() {
  return window['go']['main']['App']['Toolchains']();
}

export function Workspace() {
  return window['go']['main']['App']['Workspace']();
}
