// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRoot(arg1, arg2) {
  return window['go']['main']['App']['AddRoot'](arg1, arg2);
}

export function ChooseRoot() {
  return window['go']['main']['App']['ChooseRoot']();
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function DetectEditors() {
  return window['go']['main']['App']['DetectEditors']();
}

export function Explain(arg1, arg2) {
  return window['go']['main']['App']['Explain'](arg1, arg2);
}

export function GetGlobalEditorConfig() {
  return window['go']['main']['App']['GetGlobalEditorConfig']();
}

export function GetPreferredEditor(arg1) {
  return window['go']['main']['App']['GetPreferredEditor'](arg1);
}

export function Invalidate(arg1, arg2) {
  return window['go']['main']['App']['Invalidate'](arg1, arg2);
}

export function OpenFile(arg1, arg2) {
  return window['go']['main']['App']['OpenFile'](arg1, arg2);
}

export function OpenRoot(arg1) {
  return window['go']['main']['App']['OpenRoot'](arg1);
}

export function RefreshGit(arg1) {
  return window['go']['main']['App']['RefreshGit'](arg1);
}

export function RemoveRoot(arg1) {
  return window['go']['main']['App']['RemoveRoot'](arg1);
}

export function RenderDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenderDocument'](arg1, arg2, arg3);
}

export function RevealFile(arg1) {
  return window['go']['main']['App']['RevealFile'](arg1);
}

export function RunScript(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunScript'](arg1, arg2, arg3, arg4);
}

export function SaveGlobalEditorConfig(arg1) {
  return window['go']['main']['App']['SaveGlobalEditorConfig'](arg1);
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function SetGlobalPreferredEditor(arg1, arg2) {
  return window['go']['main']['App']['SetGlobalPreferredEditor'](arg1, arg2);
}

export function SetWorkspacePreferredEditor(arg1, arg2) {
  return window['go']['main']['App']['SetWorkspacePreferredEditor'](arg1, arg2);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function StopScript(arg1) {
  return window['go']['main']['App']['StopScript'](arg1);
}

export function ToggleFavorite(arg1, arg2) {
  return window['go']['main']['App']['ToggleFavorite'](arg1, arg2);
}

export function Toolchains() {
  return window['go']['main']['App']['Toolchains']();
}

export function Workspace() {
  return window['go']['main']['App']['Workspace']();
}
